function xdot = Unieq(Time, index_x, options, alpha)
index_a = alpha;
xdot = [(25 * index_a + 10) * (index_x(2) - index_x(1)); ...
    (28 - 35 * index_a) * index_x(1) + (29 * index_a - 1) * index_x(2) - index_x(1) * index_x(3); ...
    index_x(1) * index_x(2) - ((index_a + 8) / 3) * index_x(3)];